default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host:  localhost

development:
  <<: *default
  database: recruit_development

test:
  <<: *default
  database: recruit_test

production:
  <<: *default
  database: recruit_development
  username: postgres
  password: postgres
